### ISSUE TITLE
[Bug] Some keys not work on non-English keyboards

### ISSUE THREAD

**Issue by yawin123** [XITRIX/Moonlight-Switch#139] opened 2024-02-12 19:49 UTC
Most of the keys do not work and, if your keyboard layout is not the standard English one, forget about being able to enjoy your language comfortably.

I thought I read that part of the code was based on that of Switch-NX.  Well, in this program the keyboard does work well.  The reason for this difference could be looked at.

I like this project, but it is unacceptable that when you press the comma key the PC receives the Print Screen key.

https://github.com/XITRIX/Moonlight-Switch/assets/5033480/569d0975-7fea-45a0-85f5-d8fd2d39250c

https://github.com/XITRIX/Moonlight-Switch/assets/5033480/955a76a9-b766-420e-b33e-9e54f03ea2d2

**Comment by XITRIX** [comment] 2024-02-12 20:31
Thanks for the feedback, I'll try to check the issue. But do not use word "unacceptable", this project made on pure enthusiasm, I do not get paid for that.

**Comment by XITRIX** [comment] 2024-02-12 21:11
[Moonlight.nro.zip](https://github.com/XITRIX/Moonlight-Switch/files/14250975/Moonlight.nro.zip)
Use this build, please, enable "Show debugging view" in settings tab, and try to press the buttons that works incorrect to you

try to make the list like:
Expected button - map from - map to

After that I'll try to find why this keys works incorrectly

**Comment by yawin123** [comment] 2024-02-12 21:13
I'm on it. I hope to have the complete list tomorrow.

**Comment by yawin123** [comment] 2024-02-12 22:14
Keys that I have found do not work

| Key              |  From  | To   |
| ---                 | ---        | ---    |
| ,                    | 41       | 256 |
| .                    | 55       | 46   |
| Home          | 74       | 268 |
| End              | 77       | 269 |
| Page Up      | 75       | 266 |
| Page Down | 76      | 287 |
| <                   | 100    | -1    |
| >                   | 225    | 340 |
| '                    | 45       | 45  |
| ¡                    | 46       | 61  |
| +                   | 48       | 93  |
| ñ                   | 51       | 59   |

I think these are all the keys that are failing.

**Comment by XITRIX** [comment] 2024-02-12 22:45
Thanks, is it possible to extend it with wrong results? Sorry for not mentioning it earlier

**Comment by yawin123** [comment] 2024-02-12 22:47
In general they do not cause any results. At least about Sublime Text.

Page Up causes line breaks.
, causes the same effect as Print Screen.
The rest of the keys, as far as I remember, do nothing. Anyway, I'll look at it tomorrow just in case.

**Comment by XITRIX** [comment] 2024-02-12 22:57
Could you please check does your keyboard works on Switch, try to type some text in IP field i.e.? Because values "keys from" do not match with expected buttons at all, while it's raw data from LibNX.

For example your `,` button reported 41, while 41 is `HidKeyboardKey_Escape`
<img width="388" alt="image" src="https://github.com/XITRIX/Moonlight-Switch/assets/9553519/0bc93414-4f1c-43db-bb30-0fbf55ee6169">

**Comment by yawin123** [comment] 2024-02-12 23:00
I tested with Moonlight-NX and it works ok. That is why I considered that the problem was in this program.

Tomorrow I will look to see if there is a homebrew text editor to check that everything responds as it should.

**Comment by XITRIX** [comment] 2024-02-12 23:15
I was able to reproduce it by changing keyboard language in settings of Switch, keys not works even on normal English keyboard with Deutsch layout. Now it will be much easier to debug it

**Comment by yawin123** [comment] 2024-02-18 10:08
Sorry it took so long.  Work has kept me busy.  I'll get to that now.

**Comment by XITRIX** [comment] 2024-02-18 14:53
Check [this build](https://github.com/XITRIX/Moonlight-Switch/actions/runs/7949761232), please. I think now it should work fine.

**Comment by yawin123** [comment] 2024-02-19 12:39
Indeed, it works very well and I have not found any keys that fail. What I have found, although I don't know if it would make more sense to open a new issue for it, is that the mouse wheel does not scroll.

I don't consider it a serious problem, but I thought it appropriate to report it.

**Comment by yawin123** [comment] 2024-02-19 16:13
If you already know that there is a problem with the mouse wheel, I don't think it is necessary to open any issue.

Thank you very much for your dedication.

**Comment by XITRIX** [comment] 2024-05-27 08:28
Released in v1.1.0

**Closed by XITRIX** 2024-05-27 08:28 UTC
Labels: wait for release
