### ISSUE TITLE
About Joy-Con vibration problem

### ISSUE THREAD

**Issue by Azuuuma** [XITRIX/Moonlight-Switch#148] opened 2024-03-15 04:56 UTC
I’ve noticed that the current Joy-Con vibration intensity is too strong, which seems odd. Could you consider adding options to turn off the Joy-Con controller vibration and adjust the vibration intensity?

**Comment by XITRIX** [comment] 2024-03-15 08:45
Duplicate of #137

**Comment by XITRIX** [comment] 2024-03-15 08:45
It is already implemented, you can download Dev build and test it

**Closed by XITRIX** 2024-03-15 08:45 UTC
