### ISSUE TITLE
The streams outputs at 720p despite selecting the 1080p option

### ISSUE THREAD

**Issue by renA21** [XITRIX/Moonlight-Switch#4] opened 2021-07-29 13:23 UTC
Title says it all, and prolly UI too? Not sure if the latter is a borealis thing that only allows rendering the UI at 720p when docked.

**Comment by XITRIX** [comment] 2021-07-29 14:03
Thank you for the report, I'll try to figure it out.

**Comment by XITRIX** [comment] 2021-08-25 12:07
Could not reproduce it, but 1080p is working not so great as expected. Discussion about it here #7

**Comment by renA21** [comment] 2021-08-28 03:01
1080p doesn't work well on stock clocks but it does when overclocking the CPU--but this is not the issue I was describing. What I was referring to is that I believe that Moonlight-Switch _does_ decode the video stream at 1080p as intended, but the output is most likely downsampled to 720p instead. Moonlight-NX on the other hand does output actual 1080p frames on docked along with its UI, which leads me to believe that this is some borealis-side issue where the UI is still rendered at 720p despite being docked.

**Comment by XITRIX** [comment] 2021-08-29 19:40
Ok, I got it, but how do you see this downscale? On first glance, when I connected switch to my monitor, I'm not sure that image was downscaled, also, I've checked the code of borealis renderer, the only thing it does, is - upscaling UI, so local coordinates will be in range from 0 to 720 on any screen size, but still, as I can see it renders in native resolution, also moonlight frame renderer was taken right from moonlight-nx, so I'm not sure how to recognize the problem...
Still, I'll try to do something with it.

**Comment by renA21** [comment] 2021-08-30 14:35
I tested this on my 1080p monitor, first image is from Moonlight-Switch, and second from Moonlight-NX. Both set to 1080p resolution.

![image](https://user-images.githubusercontent.com/44066520/131356271-297c14c5-020e-49e8-be08-f9ae8c8f70c0.jpeg)

![image](https://user-images.githubusercontent.com/44066520/131356281-a2ea5ded-97ed-490b-a8c7-c02c1414d65c.jpeg)

**Comment by XITRIX** [comment] 2021-08-30 17:30
Hmm… Yes, there is the difference. The problem is, that I’m using highly modified version of borealis, so maybe I broke something by my self, but I’m absolutely sure, that borealis UI renders in native resolution, cause I cannot see any pixels on my MacBook’s screen, when app opens in full screen.

I’ll try to investigate it…

**Comment by XITRIX** [comment] 2021-08-30 19:27
Ok, I'm an idiot...
Yes, it renders UI in native resolution... but only on PC...
I don't know why, but resolution change callback not working on switch, now I had already make it work with hack, by force setting screen resolution, depending on switch mode type (portable - 720p, dock - 1080p), but I think there should be a better way of doing that.
If you'd like, I could attach a build with that hack in that issue, until I'll find a better way, and will update a release version.

[br_moonlight.nro.zip](https://github.com/XITRIX/Moonlight-Switch/files/7079070/br_moonlight.nro.zip)

**Comment by XITRIX** [comment] 2021-08-30 20:33
Ok, I think I've found not great, but good enough solution to fix it, here is the final build, check it and tell me, if it works well. 

I'll close that issue when it will be included in the final release. 

[br_moonlight.nro.zip](https://github.com/XITRIX/Moonlight-Switch/files/7079447/br_moonlight.nro.zip)

**Comment by XITRIX** [comment] 2021-08-30 21:49
Ok, I think I've found not great, but good enough solution to fix it, check it and tell me, if it works well.

Fixed in Release v0.7.1

**Closed by XITRIX** 2021-08-30 21:49 UTC

**Comment by renA21** [comment] 2021-08-31 13:41
Just tested it and can confirm that is working as intended. Thanks! I hope, you'll be able to find a better implementation of this eventually.
