### ISSUE TITLE
Possible to use screen capture key as "guide key" ? 

### ISSUE THREAD

**Issue by imkrut** [XITRIX/Moonlight-Switch#107] opened 2023-08-09 01:58 UTC
As you guys know, Nintendo allows to disable/remap the capture button, leaving an "empty" button for usage.
Is it possible for that button to be mapped to the "guide" button  of the 360 gamepad?

I normally use the guide button + others to create combos for extra features, that unfortunately, the Switch controller doesn't allow.

Alternatively, is it possible to map "sections" of the Switch touch screen to certain keyboard keys (aka, top left = f2, top right f4, bottom left = space, etc) that way you could have more buttons in theory?

Thank you!

**Comment by XITRIX** [comment] 2023-08-11 13:59
Hi, screenshot button unfortunately it's impossible to use that button to anything but screenshot

But for screen sections maaay be yes, but I'm not sure I'll have time to implement it any time soon, sorry for that

**Comment by imkrut** [comment] 2023-08-12 17:23
Even if the button is disabled for screen capture it can't be used by homebrew? damn, that sucks to have that limitation in place.

If it's of any use, Moonlight for Vita has the touchscreen functionality I mentioned ;)

https://github.com/xyzz/vita-moonlight/releases

**Comment by XITRIX** [comment] 2023-08-13 09:50
I wanted to use home button as home for streaming, and registre it in Switch system only on doubleclick, like Adrenaline on Vita works, but as I understand, even disabling this buttons do not allow to register the click by the homebrew app

**Comment by imkrut** [comment] 2023-08-20 17:59
> I wanted to use home button as "guide" for streaming, and registre it in Switch system only on doubleclick, like Adrenaline on Vita works, but as I understand, even disabling this buttons do not allow to register the click by the homebrew app

Too bad, would have been great to have an extra button.

Do you think it's possible to port the touchscreen button functionality of the vita port ?

**Comment by XITRIX** [comment] 2023-08-20 22:52
Yes, it is possible, but requires some time to implement, which, unfortunately, I have not much currently

**Comment by imkrut** [comment] 2023-08-21 23:30
> Yes, it is possible, but requires some time to implement, which, unfortunately, I have not much currently

Super understandable, I didn't mean to pressure with my comment.

I'll be looking forward to any updates on this front, thank you!

**Comment by imkrut** [comment] 2023-09-14 12:01
@XITRIX 
Since I didn't really have a place to say this, and is somewhat related. The new update performance knocks it out of the park, it's greatly improved on my end, and feels almost like playing directly on the computer through the Switch, latency is great, and even the audio got improved (tho, the default setting now is worse, IMO, changing the driver to the alternative also removes any crackling on the old version).

Touchscreen seem to be working much better, tho, I tried some lightgun games to see how it fared, and touching doesn't actually map as a click.

Anyway, just wanted to say thank you, it's a noticeable improvement, and using Moonlight with a homescreen forwarder is just magic in terms of convenience.

I also noticed that now the recording button has been disabled, is this somehow related to the original post?

Thanks gain

**Comment by XITRIX** [comment] 2023-09-14 16:21
@imkrut, no ... screenshots should work ... Need to check it, but I think I've made some screenshots not so far ago

**Comment by frank-owen** [comment] 2024-01-01 17:58
Is it possible to map some other button combination to the guide key without interfering with other functions? Using Left Stick + Right Stick seems like it would work from an end user perspective. The guide key would be quite useful for Steam Big Picture to shutdown the system/change game.

**Comment by XITRIX** [comment] 2024-02-06 19:47
Duplicate of #132

**Comment by XITRIX** [comment] 2024-02-06 19:47
Opened a new issue for onscreen guide button

**Closed by XITRIX** 2024-02-06 19:47 UTC
