### ISSUE TITLE
Is it possible to add a function about using gyroscope?

### ISSUE THREAD

**Issue by captainbanana233** [XITRIX/Moonlight-Switch#87] opened 2023-01-19 15:41 UTC
Hi there!
It is a great project! I found that Steam will recoginize the handle as XBOX 360，it leads to we could not use gyroscope to play games through moonlight. Is it possible to add a function about using gyroscope?

**Comment by XITRIX** [comment] 2023-01-29 09:20
Hi, I think not moonlight, not Nvidia Shield supports it, so I'm afraid it's impossible to make without extra 2d party software

**Comment by ld892012** [comment] 2023-02-18 10:45
Maybe add possibility to create a DSU server with Moonlight-Switch ?
It not solve your problem but it gives ability to use Switch as a WiiU GamePad for Cemu emulator, lots of persons use Android in their Switch with Moonlight and MotionSource but Android on Switch as some WiFi issues.
Alternatively, [Sunshine](https://github.com/LizardByte/Sunshine) give possibility to emulate DS4 controller instead of X360 but the gyroscope isn't transferred by Moonlight.

**Comment by XITRIX** [comment] 2024-01-31 17:41
Closed as duplicate of #98

**Closed by XITRIX** 2024-01-31 17:41 UTC
